services:
  - type: web
    name: board-games-api
    runtime: python3
    buildCommand: "./build.sh"
    startCommand: "gunicorn board_games.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: DATABASE_URL
        fromDatabase:
          name: board-games-db
          property: connectionString